version: '3.1'
services:
  web:
    build:
      context: ../
      dockerfile: ./docker/cakephp/Dockerfile
    volumes:
      - ./html/app:/var/www/html/app
    environment:
      APP_DATABASE_HOST: db
      APACHE_DOCUMENT_ROOT: /var/www/html/app/webroot
    ports:
      - "8080:80"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    build:
      context: ../
      dockerfile: ./docker/mysql/Dockerfile
    environment:
        - MYSQL_DATABASE=app_development
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
